### ISSUE TITLE
Black, White and Transparent options included when not selected

### ISSUE THREAD

**Issue by richhayler** [fruitstudios/craft-colorit#3]
Despite leaving the transparent, black and white color options unchecked when adding a new ColorIt field these options are included on the front end entry form.

Can this be fixed so only the selected options appear please.

**Comment by swixpop** [comment]
+1

**Comment by samhibberd** [comment]
Fixed in https://github.com/fruitstudios/craft-colorit/releases/tag/1.0.6. Thanks.
