### ISSUE TITLE
Change: Remove !important CSS declarations

### ISSUE THREAD

**Issue by richhayler** [fruitstudios/craft-colorit#5]
Please can you remove the "!important" CSS declarations from the plugin input template. The inline background style is sufficient and will work fine without it. Having !important inline prevents the background colour from being overridden by custom styles set in the control panel. 

`<li class="colorit--palette-color" style="background:#FFFFFF;"></li>`

My specific use case is on a multisite install. I have a colorIt field defined in "Globals" named "theme" which I use to set the website theme. I then have another colorIt field I use on entry pages. I would like the colours on the entry pages to reflect the colour scheme that is defined for that particular site in globals. I could achieve this by overriding the inline "background" style using CSS defined in the control panel if the !important rules were removed.

**Comment by samhibberd** [comment]
Fixed in https://github.com/fruitstudios/craft-colorit/releases/tag/1.0.6. Thanks.
