### ISSUE TITLE
Can't update from command line

### ISSUE THREAD

**Issue by swixpop** [fruitstudios/craft-colorit#6]
Version on packagist is lagging. https://packagist.org/packages/fruitstudios/palette

**Comment by samhibberd** [comment]
Hey @swixpop, looks like there are some old packages (it used to be called palette) that have not been cleaned up in packagist. Sorry for any confusion, all cleaned up now and Installation instructions updated in the docs:

https://github.com/fruitstudios/craft-colorit#installation

Thanks for letting us know!
