### ISSUE TITLE
Javascript Error when using ColorIt field in Globals

### ISSUE THREAD

**Issue by richhayler** [fruitstudios/craft-colorit#8]
Please reference https://github.com/craftcms/cms/issues/3452

I'm getting the following Javascript error in the control panel in the Globals section where I am using a ColorIt field.

`[Error] TypeError: null is not an object (evaluating 'dom.palette.addEventListener')
init (Colorit.js:187)
constructor (Colorit.js:210)
Global Code (global:1787)`

**Comment by samhibberd** [comment]
@richhayler I can't recreate this. Can you give me a little more browser info: https://www.whatsmybrowser.org/

**Comment by richhayler** [comment]
It’s happening in Safari on macOS 10.14, and Safari on iOS 12 (tested on iPad and iPhone).

**Comment by richhayler** [comment]
https://whatsmybrowser.org/b/BZU7PE5

**Comment by samhibberd** [comment]
Still nothing, do you have a staging version I can access?

**Comment by richhayler** [comment]
Yes, I will email the details through. Thank you.

**Comment by samhibberd** [comment]
Thanks, got it and worked it out. Not seen only the custom colour input used before, nice! 

Will get a fix out tonight.

**Comment by richhayler** [comment]
Any update on the fix?

**Comment by samhibberd** [comment]
Fixed in [1.0.7](https://github.com/fruitstudios/craft-colorit/releases/tag/1.0.7)

**Comment by richhayler** [comment]
Thank you
